const quotes = [
    "Success is not final, failure is not fatal: It is the courage to continue that counts. <br>- Winston Churchill",
    "Believe you can and you're halfway there. <br>- Theodore Roosevelt",
    "The only limit to our realization of tomorrow will be our doubts of today. <br>- Franklin D. Roosevelt",
    "Your time is limited, don't waste it living someone else's life. <br>- Steve Jobs",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. <br>- Christian D. Larson",
    "The only way to do great work is to love what you do. <br>- Steve Jobs",
    "Don't watch the clock; do what it does. Keep going. <br>- Sam Levenson",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. <br>- Roy T. Bennett",
    "You miss 100% of the shots you don't take. <br>- Wayne Gretzky",
    "The secret of getting ahead is getting started. <br>- Mark Twain",
    "Success is not in what you have, but who you are. <br>- Bo Bennett",
    "You are never too old to set another goal or to dream a new dream. <br>- C.S. Lewis",
    "If you can dream it, you can achieve it. <br>- Zig Ziglar",
    "The only person you are destined to become is the person you decide to be. <br>- Ralph Waldo Emerson",
    "It does not matter how slowly you go as long as you do not stop. <br>- Confucius",
    "The only place where success comes before work is in the dictionary. <br>- Vidal Sassoon",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this. <br>- Chantal Sutherland",
    "Success is not how high you have climbed, but how you make a positive difference to the world. <br>- Roy T. Bennett",
    "Success is not just about making money. It's about making a difference. <br>- Unknown",
    "The future belongs to those who believe in the beauty of their dreams. <br>- Eleanor Roosevelt",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. <br>- Steve Jobs",
    "The only limit to our realization of tomorrow will be our doubts of today. <br>- Franklin D. Roosevelt",
    "If you want to achieve greatness stop asking for permission. <br>- Unknown",
    "You are never too old to set another goal or to dream a new dream. <br>- C.S. Lewis",
    "Don't watch the clock; do what it does. Keep going. <br>- Sam Levenson",
    "Believe you can and you're halfway there. <br>- Theodore Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. <br>- Winston Churchill",
    "The secret of getting ahead is getting started. <br>- Mark Twain",
    "You miss 100% of the shots you don't take. <br>- Wayne Gretzky",
    "The future belongs to those who believe in the beauty of their dreams. <br>- Eleanor Roosevelt",
    "Success is not in what you have, but who you are. <br>- Bo Bennett",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. <br>- Roy T. Bennett",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. <br>- Christian D. Larson",
    "If you can dream it, you can achieve it. <br>- Zig Ziglar",
    "The only person you are destined to become is the person you decide to be. <br>- Ralph Waldo Emerson",
    "It does not matter how slowly you go as long as you do not stop. <br>- Confucius",
    "The only place where success comes before work is in the dictionary. <br>- Vidal Sassoon",
    "Success is not how high you have climbed, but how you make a positive difference to the world. <br>- Roy T. Bennett",
    "Success is not just about making money. It's about making a difference. <br>- Unknown",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this. <br>- Chantal Sutherland",
    "Your time is limited, don't waste it living someone else's life. <br>- Steve Jobs",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. <br>- Steve Jobs",
    "If you want to achieve greatness stop asking for permission. <br>- Unknown",
    "Success is not about the destination, it's about the journey. <br>- Unknown",
    "Challenges are what make life interesting, and overcoming them is what makes life meaningful. <br>- Joshua J. Marine",
    "You have to be at your strongest when you're feeling at your weakest. <br>- Unknown",
    "Your hardest times often lead to the greatest moments of your life. Keep going. <br>- Unknown",
    "Happiness is not by chance, but by choice. <br>- Jim Rohn",
    "The only way to do great work is to love what you do. <br>- Steve Jobs",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. <br>- Christian D. Larson",
    "The only limit to our realization of tomorrow will be our doubts of today. <br>- Franklin D. Roosevelt",
    "If you can dream it, you can achieve it. <br>- Zig Ziglar",
    "The only person you are destined to become is the person you decide to be. <br>- Ralph Waldo Emerson",
    "It does not matter how slowly you go as long as you do not stop. <br>- Confucius",
    "The only place where success comes before work is in the dictionary. <br>- Vidal Sassoon",
];